import { classNames } from '@/utils/commonUtils';
import { Button } from '@/components/common/buttons';
import { components } from '@/api/types/case';
import { inputClassName, labelClassName } from '@/components/common/input';
import { useState } from 'react';

type CreationStatusEnum = components['schemas']['CreationStatusEnum'];
const CREATION_STATUS_OPTIONS: CreationStatusEnum[] = ['autogenerated', 'verified', 'manual'];
type Props = {
  initialData?: components['schemas']['CaseDetailRequest'];
  onSubmit: (data: components['schemas']['CaseDetailRequest']) => void;
  onCancel: () => void;
  isPending?: boolean;
  submitLabel?: string;
};

function CaseForm({
  initialData,
  onSubmit,
  onCancel,
  isPending,
  submitLabel = 'Save Changes',
}: Props) {
  const [draftDataUpdate, setDraftDataUpdate] = useState<
    components['schemas']['CaseDetailRequest']
  >(
    initialData ?? {
      title: '',
      description: '',
      type: '',
      creationStatus: 'manual',
      trelloUrl: '',
      alias: [],
    }
  );

  const caseDataOnChange = (field: keyof typeof draftDataUpdate, value: string) => {
    setDraftDataUpdate((prev) => ({ ...prev, [field]: value }));
  };

  return (
    <div className='rounded-xl bg-white shadow-sm ring-1 ring-gray-900/5 dark:bg-gray-900 dark:ring-white/10'>
      <div className='p-6 sm:p-8'>
        {/* Form Fields */}
        <div className='grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3'>
          {/* Title */}
          <div className='sm:col-span-2 lg:col-span-3'>
            <label htmlFor='title' className={labelClassName}>
              Title
            </label>
            <input
              id='title'
              type='text'
              value={draftDataUpdate.title ?? ''}
              onChange={(e) => caseDataOnChange('title', e.target.value)}
              placeholder='Enter case title'
              className={inputClassName}
            />
          </div>

          {/* Type */}
          <div>
            <label htmlFor='type' className={labelClassName}>
              Type
            </label>
            <input
              id='type'
              type='text'
              value={draftDataUpdate.type ?? ''}
              onChange={(e) => caseDataOnChange('type', e.target.value)}
              placeholder='Enter type'
              className={inputClassName}
            />
          </div>

          {/* Creation Status */}
          <div>
            <label htmlFor='creationStatus' className={labelClassName}>
              Creation Status
            </label>
            <select
              id='creationStatus'
              value={draftDataUpdate.creationStatus}
              onChange={(e) => caseDataOnChange('creationStatus', e.target.value)}
              className={inputClassName}
            >
              {CREATION_STATUS_OPTIONS.map((v) => (
                <option key={v} value={v}>
                  {v.charAt(0).toUpperCase() + v.slice(1)}
                </option>
              ))}
            </select>
          </div>

          {/* Trello URL */}
          <div>
            <label htmlFor='trelloUrl' className={labelClassName}>
              Trello URL
            </label>
            <input
              id='trelloUrl'
              type='url'
              value={draftDataUpdate.trelloUrl ?? ''}
              onChange={(e) => caseDataOnChange('trelloUrl', e.target.value)}
              placeholder='https://trello.com/...'
              className={inputClassName}
            />
          </div>

          {/* Alias */}
          <div className='sm:col-span-2 lg:col-span-3'>
            <label className={labelClassName}>Alias</label>
            <div className='space-y-2'>
              {(draftDataUpdate.alias ?? []).map((item, index) => (
                <div key={index} className='flex items-center gap-2'>
                  <input
                    type='text'
                    value={item}
                    onChange={(e) => {
                      const newAlias = [...(draftDataUpdate.alias ?? [])];
                      newAlias[index] = e.target.value;
                      setDraftDataUpdate((prev) => ({ ...prev, alias: newAlias }));
                    }}
                    placeholder='Enter alias'
                    className={classNames(inputClassName, 'flex-1')}
                  />
                  <button
                    type='button'
                    onClick={() => {
                      const newAlias = (draftDataUpdate.alias ?? []).filter((_, i) => i !== index);
                      setDraftDataUpdate((prev) => ({ ...prev, alias: newAlias }));
                    }}
                    className='rounded-md bg-red-50 px-3 py-2 text-sm font-medium text-red-700 transition-colors hover:bg-red-100 dark:bg-red-900/20 dark:text-red-400 dark:hover:bg-red-900/30'
                  >
                    Remove
                  </button>
                </div>
              ))}
              <button
                type='button'
                onClick={() => {
                  setDraftDataUpdate((prev) => ({
                    ...prev,
                    alias: [...(prev.alias ?? []), ''],
                  }));
                }}
                className='rounded-md bg-blue-50 px-4 py-2 text-sm font-medium text-blue-700 transition-colors hover:bg-blue-100 dark:bg-blue-900/20 dark:text-blue-400 dark:hover:bg-blue-900/30'
              >
                + Add Alias
              </button>
            </div>
          </div>

          {/* Description */}
          <div className='sm:col-span-2 lg:col-span-3'>
            <label htmlFor='description' className={labelClassName}>
              Description
            </label>
            <textarea
              id='description'
              value={draftDataUpdate.description ?? ''}
              onChange={(e) => caseDataOnChange('description', e.target.value)}
              placeholder='Enter case description'
              rows={4}
              className={classNames(inputClassName, 'resize-vertical')}
            />
          </div>
        </div>

        {/* Action Buttons */}
        <div className='mt-8 flex items-center justify-end gap-3 pt-6'>
          <Button onClick={onCancel} type='red' size='md' className='px-6'>
            Cancel
          </Button>
          <Button
            onClick={() => onSubmit(draftDataUpdate)}
            type='green'
            size='md'
            disabled={isPending}
            className='px-6 shadow-sm transition-shadow duration-200 hover:shadow-md'
          >
            {submitLabel}
          </Button>
        </div>
      </div>
    </div>
  );
}

export default CaseForm;
