import React, { useState } from 'react';
import { caseDetailPath, useMutationCaseUpdate, useQueryCaseDetailObject } from '@/api/case';
import { classNames } from '@/utils/commonUtils';
import { Button } from '@/components/common/buttons';
import { useNavigate, useParams } from 'react-router-dom';
import { components } from '@/api/types/case';
import { inputClassName, labelClassName } from '@/components/common/input';
import { SpinnerWithText } from '@/components/common/spinner';
import toaster from '@/components/common/toaster';
import { DetailedErrorBoundary } from '@/components/common/error';
import { useQueryClient } from '@tanstack/react-query';

type CreationStatusEnum = components['schemas']['CreationStatusEnum'];
const CREATION_STATUS_OPTIONS: CreationStatusEnum[] = ['autogenerated', 'verified', 'manual'];

export function CaseEditForm({ caseOrcabusId }: { caseOrcabusId: string }) {
  const navigate = useNavigate();
  const queryClient = useQueryClient();

  const caseModel = useQueryCaseDetailObject({
    params: { path: { orcabusId: caseOrcabusId } },
  });
  const caseData = caseModel.data;

  const [draftDataUpdate, setDraftDataUpdate] = useState<
    components['schemas']['PatchedCaseDetailRequest']
  >({
    title: caseData.title,
    description: caseData.description,
    type: caseData.type,
    creationStatus: caseData.creationStatus,
    trelloUrl: caseData.trelloUrl,
  });

  const caseDataOnChange = (field: keyof typeof draftDataUpdate, value: string | number) => {
    setDraftDataUpdate((prev) => ({ ...prev, [field]: value }));
  };

  const { isPending, isError, error, mutate } = useMutationCaseUpdate({
    orcabusId: caseOrcabusId,
    body: draftDataUpdate,
    reactQuery: {
      onSuccess: async () => {
        await queryClient.invalidateQueries({
          queryKey: ['GET', caseDetailPath, { path: { orcabusId: caseOrcabusId } }],
        });
        toaster.success({ title: 'Changes saved' });
        navigate(`/case/${caseOrcabusId}`, { replace: true });
      },
    },
  });

  if (isPending) {
    return <SpinnerWithText text='Saving changes ...' />;
  }

  if (isError) {
    throw error;
  }

  return (
    <>
      {/* Header Section */}

      {/* Form Card */}
      <div className='rounded-xl bg-white shadow-sm ring-1 ring-gray-900/5 dark:bg-gray-900 dark:ring-white/10'>
        <div className='p-6 sm:p-8'>
          {/* Form Fields */}
          <div className='grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3'>
            {/* Title */}
            <div className='sm:col-span-2 lg:col-span-3'>
              <label htmlFor='title' className={labelClassName}>
                Title
              </label>
              <input
                id='title'
                type='text'
                value={draftDataUpdate.title ?? ''}
                onChange={(e) => caseDataOnChange('title', e.target.value)}
                placeholder='Enter case title'
                className={inputClassName}
              />
            </div>

            {/* Type */}
            <div>
              <label htmlFor='type' className={labelClassName}>
                Type
              </label>
              <input
                id='type'
                type='text'
                value={draftDataUpdate.type ?? ''}
                onChange={(e) => caseDataOnChange('type', e.target.value)}
                placeholder='Enter type'
                className={inputClassName}
              />
            </div>

            {/* Creation Status */}
            <div>
              <label htmlFor='creationStatus' className={labelClassName}>
                Creation Status
              </label>
              <select
                id='creationStatus'
                value={draftDataUpdate.creationStatus}
                onChange={(e) => caseDataOnChange('creationStatus', e.target.value)}
                className={inputClassName}
              >
                {CREATION_STATUS_OPTIONS.map((v) => (
                  <option key={v} value={v}>
                    {v.charAt(0).toUpperCase() + v.slice(1)}
                  </option>
                ))}
              </select>
            </div>

            {/* Trello URL */}
            <div>
              <label htmlFor='trelloUrl' className={labelClassName}>
                Trello URL
              </label>
              <input
                id='trelloUrl'
                type='url'
                value={draftDataUpdate.trelloUrl ?? ''}
                onChange={(e) => caseDataOnChange('trelloUrl', e.target.value)}
                placeholder='https://trello.com/...'
                className={inputClassName}
              />
            </div>

            {/* Description */}
            <div className='sm:col-span-2 lg:col-span-3'>
              <label htmlFor='description' className={labelClassName}>
                Description
              </label>
              <textarea
                id='description'
                value={draftDataUpdate.description ?? ''}
                onChange={(e) => caseDataOnChange('description', e.target.value)}
                placeholder='Enter case description'
                rows={4}
                className={classNames(inputClassName, 'resize-vertical')}
              />
            </div>
          </div>

          {/* Action Buttons */}
          <div className='mt-8 flex items-center justify-end gap-3 border-t border-gray-200 pt-6 dark:border-gray-700'>
            <Button
              onClick={() => navigate(`/case/${caseOrcabusId}`)}
              type='red'
              size='md'
              className='px-6'
            >
              Cancel
            </Button>
            <Button
              onClick={() => mutate()}
              type='green'
              size='md'
              className='px-6 shadow-sm transition-shadow duration-200 hover:shadow-md'
            >
              Save Changes
            </Button>
          </div>
        </div>
      </div>
    </>
  );
}

export default function CaseEditPage() {
  const { caseOrcabusId } = useParams();
  if (!caseOrcabusId) {
    throw new Error('No case id in URL path!');
  }
  return (
    <div className='mx-auto max-w-7xl p-6'>
      <div className='mb-8'>
        <div className='mb-2 flex items-center gap-3'>
          <h1 className='text-3xl font-bold text-slate-900 dark:text-white'>Edit Case</h1>
        </div>
        <p className='text-sm text-slate-600 dark:text-slate-400'>
          Update case details for{' '}
          <span className='inline-flex items-center rounded-md bg-blue-50 px-2.5 py-1 font-mono text-sm font-semibold text-blue-700 ring-1 ring-blue-700/10 ring-inset dark:bg-blue-900/30 dark:text-blue-300 dark:ring-blue-400/30'>
            {caseOrcabusId}
          </span>
        </p>
      </div>
      <DetailedErrorBoundary>
        <CaseEditForm caseOrcabusId={caseOrcabusId} />
      </DetailedErrorBoundary>
    </div>
  );
}
